---
title: "Working with Tabular Data"
author: "Amalan, Vicky Daniel"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
subtitle: Analysis of Wines
---

```{r setup, include=FALSE}
library(knitr)

df.wines <- read.csv(file = "whitewines.csv", header = F)
if (is.na(as.numeric(df.wines[1, 1]))) {
  df.wines <- read.csv(file = "whitewines.csv", header = T)
} else {
  df.wines <- read.csv(file = "whitewines.csv", header = F)
}
```
```{r calculations, include=FALSE}
total.wines <- nrow(df.wines)
percentage.over11 <- round(sum(df.wines$alcohol > 11) / total.wines * 100, 1)
highest.alcohol <- max(df.wines$alcohol)

```

There are a total of `r total.wines` wines in this data set. *`r percentage.over11`*% of the wines have an alcohol content over 11%. The highest alcohol content of any wine is *`r highest.alcohol`*%.

The scatter plot below illustrates the correlation between alcohol and sugar content.

```{css, echo=FALSE}
.title-center-blue {
  text-align: center;
  color: blue;
  font-weight: bold;
}
```


### Sugar vs Alcohol Content {.title-center-blue}
```{r scatterPlot, echo=FALSE, fig.align='center'}
plot(df.wines$residual.sugar, df.wines$alcohol,
     xlab = "Sugar", ylab = "Alcohol",
     main = "",
     pch = 1, cex = 0.8, col = "black")

```

